server {
    listen 80;
    listen [::]:80;
    server_name oracle1.1223344.xyz;

    location ^~ /.well-known/acme-challenge/ {
        alias /var/lib/acme-challenge/;
        default_type text/plain;
    }

    location /fhlun/ {
        alias /var/lib/fhlun-core/;
        autoindex off;
        default_type application/octet-stream;
        limit_except GET HEAD { deny all; }
    }

    location / { return 404; }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name oracle1.1223344.xyz;

    ssl_certificate /etc/nginx/fhlun-mirror/cert.crt;
    ssl_certificate_key /etc/nginx/fhlun-mirror/private.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    location /fhlun/ {
        alias /var/lib/fhlun-core/;
        autoindex off;
        default_type application/octet-stream;
        limit_except GET HEAD { deny all; }
    }

    location / { return 404; }
}
